# Generated by Django 5.2 on 2025-04-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celestialbody',
            name='order_from_sun',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
